AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  youtube-video

  Sample SAM Template for youtube-video

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  VideosFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: videos/
      Handler: app.app
      Runtime: python3.6
      Events:
        Videos:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        ListVideos:
          Type: Api
          Properties:
            Path: /videos
            Method: get
        CreateVideo:
          Type: Api
          Properties:
            Path: /videos
            Method: post
        ListVideo:
          Type: Api
          Properties:
            Path: /video/{videoId}/
            Method: get
        UpdateVideo:
          Type: Api
          Properties:
            Path: /video/{videoId}/
            Method: put
        DeleteVideo:
          Type: Api
          Properties:
            Path: /video/{videoId}/
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VideosApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  VideosFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt VideosFunction.Arn
  VideosFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt VideosFunctionRole.Arn
